### ISSUE TITLE
App Crashes on using library

### ISSUE THREAD

**Issue by rishavsingla** [glomadrian/Grav#22]
Attempt to invoke **Vector.iterate()** on a null object reference.

**Comment by GauravCreed** [comment]
@rishavsingla 

Same error here, got any solution?

`java.lang.RuntimeException: Unable to start activity ComponentInfo{bible.kingjamesbiblelite/com.bible.kingjamesbiblelite.ac.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.Vector.iterator()' on a null object reference
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2925)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
                                                                                 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                                 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                                 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                 at android.os.Looper.loop(Looper.java:193)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6762)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by rishavsingla** [comment]
i just implement null check condition for it nothing else

**Comment by akardas16** [comment]
**Resolved**

Go to GrawView clas and change `private Vector<ValueAnimator> gravAnimators;` to ` private Vector<ValueAnimator> gravAnimators=new Vector<>();`  the gravAnimators variable didnt initiliazed so when start() method runs, gravAnimators  gives null reference. it should be 
 ` ```
 private PointGenerator pointGenerator;
  private PaintGenerator paintGenerator;
  private Vector<GravAnimatorGenerator> gravAnimatorGenerators;
  private GravGenerator gravGenerator;
  private Vector<Grav> gravVector;
  private Vector<ValueAnimator> gravAnimators=new Vector<>();
  private ValueAnimator viewRefreshAnimator;`
```
